### ISSUE TITLE
Pangolin with Tailscale

### ISSUE THREAD

**Issue by A4alli** [hhftechnology/newt-cloudflare-tailscale-integration#1]
After just running
```
services:
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    container_name: synapse
    depends_on:
      - synapse-db
    restart: always
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - UID=1000
      - GID=1000
    volumes:
      - /home/lee/synapse:/data
    networks:
      - synapse

  synapse-db:
    image: docker.io/postgres:15-alpine
    container_name: synapse-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=mar
      - POSTGRES_PASSWORD=K95P
      - POSTGRES_DB=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /home/lee/synapse-db/schemas:/var/lib/postgresql/data
    networks:
      - synapse

  secure-proxy:
    image: hhftechnology/newt-cloudflare-tailscale-integration:latest
    cap_add:
      - NET_ADMIN
    environment:
      - ENABLE_NEWT=false
      - ENABLE_CLOUDFLARE=false
      - ENABLE_TAILSCALE=true
      - TAILSCALE_AUTH_KEY=tskey-auth-xyz
      - TAILSCALE_HOSTNAME=matrix
      - TARGET_PORTS=8008
    volumes:
      - /home/lee/data/tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - synapse

networks:
  synapse:
    name: synapse
```

how can I setup my Pangolin which is running on VPS so I can only access my matrix via Tailscale and never expose to internet?
Need some Guide to be written in the repo.
Kindly
